user  nginx;
worker_processes  auto;
# 老内核(CentOS7/3.10)上 nginx 向 /run/nginx.pid 写 pid 会 EPERM，改到 /tmp 规避
pid /tmp/nginx.pid;
error_log  /var/log/nginx/error.log warn;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # docker 内网 DNS，用于 upstream 主机名解析
    resolver 127.0.0.11 valid=10s ipv6=off;

    include /etc/nginx/conf.d/*.conf;
}
